import os
import re
import asyncio
import tempfile
import urllib.parse
from typing import AsyncGenerator
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

import base64, tempfile
from fastapi import WebSocket, WebSocketDisconnect

from src.graph.build import build_graph
from src.tts.kokoro_provider import KokoroTTSProvider
from src.stt.qwen_asr_provider import QwenASRProvider
from src.tts.wav_utils import pcm_to_wav_bytes

from fastapi.staticfiles import StaticFiles

app = FastAPI(title="LangGraph Voice Agent - Speech-to-Speech Streaming")

# Lazy/cached initialization of pipeline components
graph = build_graph()
tts_provider = KokoroTTSProvider()
stt_provider = QwenASRProvider()

SENTENCE_SPLIT_REGEX = re.compile(r"(?<=[.!?\n])\s+")


class AgentQueryRequest(BaseModel):
    query: str
    asset_id: str = "22"
    voice: str = "af_heart"
    thread_id: str = "default_session"


async def stream_graph_sentences(query: str, asset_id: str, thread_id: str) -> AsyncGenerator[str, None]:
    """Streams sentence-buffered responses from LangGraph agent execution."""
    initial_input = {
        "query": query,
        "asset_id": asset_id,
        "messages": [{"role": "user", "content": query}],
    }
    config = {"configurable": {"thread_id": thread_id}}
    buffer = ""

    async for event in graph.astream(initial_input, config=config):
        text_chunk = ""
        if isinstance(event, dict):
            for _, node_output in event.items():
                if isinstance(node_output, dict):
                    for key in ["response", "final_response", "generation", "output", "summary", "content"]:
                        val = node_output.get(key)
                        if isinstance(val, str) and val.strip():
                            text_chunk += val + " "
                    messages = node_output.get("messages")
                    if isinstance(messages, list) and messages:
                        last_msg = messages[-1]
                        content = getattr(last_msg, "content", None)
                        if isinstance(content, str) and content.strip():
                            text_chunk += content + " "

        if not text_chunk:
            continue

        buffer += text_chunk
        parts = SENTENCE_SPLIT_REGEX.split(buffer)
        if len(parts) > 1:
            for sentence in parts[:-1]:
                clean = sentence.strip()
                if clean:
                    yield clean + "\n\n"
            buffer = parts[-1]

    remaining = buffer.strip()
    if remaining:
        yield remaining + "\n"


async def stream_audio_chunks(query: str, asset_id: str, voice: str, thread_id: str) -> AsyncGenerator[bytes, None]:
    """Converts buffered agent text chunks into PCM audio bytes via Kokoro TTS."""
    synth_fn = getattr(tts_provider, "synthesize_stream_bytes", getattr(tts_provider, "synthesize", None))
    async for sentence in stream_graph_sentences(query, asset_id, thread_id):
        # Strip markdown syntax symbols and bracketed citations for vocalization
        clean_text = re.sub(r"\[\d+(?:-\d+)?\]", "", sentence)
        clean_text = re.sub(r"[*#_`]", "", clean_text).strip()
        if clean_text and synth_fn:
            audio_bytes = await asyncio.to_thread(synth_fn, clean_text, voice)
            if audio_bytes and isinstance(audio_bytes, (bytes, bytearray)):
                yield bytes(audio_bytes)


@app.post("/agent/stream-text")
async def agent_text_endpoint(req: AgentQueryRequest):
    """Streams sentence chunks generated by the LangGraph agent."""
    return StreamingResponse(
        stream_graph_sentences(req.query, req.asset_id, req.thread_id),
        media_type="text/plain",
    )


@app.post("/agent/stream-audio")
async def agent_audio_endpoint(req: AgentQueryRequest):
    """Text-to-Speech: Streams audio directly from text input through the agent."""
    return StreamingResponse(
        stream_audio_chunks(req.query, req.asset_id, req.voice, req.thread_id),
        media_type="audio/pcm",
    )


@app.post("/stt/transcribe")
async def transcribe_endpoint(file: UploadFile = File(...)):
    """Transcribes an uploaded audio file using Qwen3-ASR."""
    suffix = f".{file.filename.split('.')[-1]}" if "." in (file.filename or "") else ".wav"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(await file.read())
        tmp_path = tmp.name

    try:
        transcription_fn = getattr(stt_provider, "transcribe_with_language", getattr(stt_provider, "transcribe", None))
        result = await asyncio.to_thread(transcription_fn, tmp_path)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    if isinstance(result, dict):
        return result
    return {"text": str(result)}


@app.post("/agent/speech-to-speech")
async def speech_to_speech_endpoint(
    file: UploadFile = File(...),
    asset_id: str = Form("22"),
    voice: str = Form("af_heart"),
    thread_id: str = Form("voice_session"),
):
    """
    End-to-End Voice Pipeline:
    1. Transcribes incoming WAV/MP3 via Qwen3-ASR
    2. Runs query through LangGraph Agent (RAG on Qdrant)
    3. Streams back synthesized Kokoro TTS audio bytes
    """
    suffix = f".{file.filename.split('.')[-1]}" if "." in (file.filename or "") else ".wav"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(await file.read())
        tmp_path = tmp.name

    try:
        transcription = await asyncio.to_thread(stt_provider.transcribe, tmp_path)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    # Extract clean text whether output is string or dict
    if isinstance(transcription, dict):
        transcribed_text = transcription.get("text", "")
    else:
        transcribed_text = str(transcription or "")

    transcribed_text = transcribed_text.strip()
    if not transcribed_text:
        raise HTTPException(status_code=400, detail="No speech detected in audio file.")

    # URL-encode header value to comply with Latin-1 HTTP header specifications
    safe_header_text = urllib.parse.quote(transcribed_text)

    return StreamingResponse(
        stream_audio_chunks(
            query=transcribed_text,
            asset_id=asset_id,
            voice=voice,
            thread_id=thread_id,
        ),
        media_type="audio/pcm",
        headers={"X-Transcribed-Text": safe_header_text},
    )
    
    


@app.websocket("/ws/converse")
async def converse_ws(ws: WebSocket):
    await ws.accept()
    try:
        while True:
            msg = await ws.receive_json()

            if msg["type"] == "audio":
                wav_bytes = base64.b64decode(msg["data"])
                with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
                    tmp.write(wav_bytes)
                    tmp_path = tmp.name
                transcript = await asyncio.to_thread(stt_provider.transcribe, tmp_path)
                os.remove(tmp_path)
                query = transcript if isinstance(transcript, str) else transcript.get("text", "")
                await ws.send_json({"type": "transcript", "data": query})
            else:
                query = msg["data"]

            asset_id = msg.get("asset_id", "22")
            thread_id = msg.get("thread_id", "default_session")
            voice = msg.get("voice", "af_heart")

            async for sentence in stream_graph_sentences(query, asset_id, thread_id):
                await ws.send_json({"type": "text_chunk", "data": sentence})
                clean = re.sub(r"\[\d+(?:-\d+)?\]", "", sentence)
                clean = re.sub(r"[*#_`]", "", clean).strip()
                if clean:
                    pcm = await asyncio.to_thread(tts_provider.synthesize_stream_bytes, clean, voice)
                    wav = pcm_to_wav_bytes(pcm)
                    await ws.send_json({"type": "audio_chunk", "data": base64.b64encode(wav).decode()})

            await ws.send_json({"type": "done"})
    except WebSocketDisconnect:
        pass
    
    
    
app.mount("/", StaticFiles(directory="frontend", html=True), name="frontend")

    