import os
import re
import asyncio
import tempfile
import urllib.parse
from pathlib import Path
from typing import AsyncGenerator

from fastapi import FastAPI, UploadFile, File, Form, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from src.graph.build import build_graph
from src.tts.kokoro_provider import KokoroTTSProvider
from src.stt.qwen_asr_provider import QwenASRProvider
from src.tts.wav_utils import pcm_to_wav_bytes

app = FastAPI(title="LangGraph Voice Agent - Speech-to-Speech Streaming")

# Enable CORS for browser access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Static files path resolution
FRONTEND_DIR = Path(__file__).resolve().parent.parent / "frontend"

# Cached pipeline singletons
graph = build_graph()
tts_provider = KokoroTTSProvider()
stt_provider = QwenASRProvider()

SENTENCE_SPLIT_REGEX = re.compile(r"(?<=[.!?\n])\s+")


class AgentQueryRequest(BaseModel):
    query: str
    asset_id: str = "22"
    voice: str = "af_heart"
    thread_id: str = "default_session"


async def stream_graph_sentences(query: str, asset_id: str, thread_id: str) -> AsyncGenerator[str, None]:
    """Streams sentence-buffered responses from LangGraph agent execution."""
    initial_input = {
        "query": query,
        "asset_id": asset_id,
        "messages": [{"role": "user", "content": query}],
    }
    config = {"configurable": {"thread_id": thread_id}}
    buffer = ""

    async for event in graph.astream(initial_input, config=config):
        text_chunk = ""
        if isinstance(event, dict):
            for _, node_output in event.items():
                if isinstance(node_output, dict):
                    for key in ["response", "final_response", "generation", "output", "summary", "content"]:
                        val = node_output.get(key)
                        if isinstance(val, str) and val.strip():
                            text_chunk += val + " "
                    messages = node_output.get("messages")
                    if isinstance(messages, list) and messages:
                        last_msg = messages[-1]
                        content = getattr(last_msg, "content", None)
                        if isinstance(content, str) and content.strip():
                            text_chunk += content + " "

        if not text_chunk:
            continue

        buffer += text_chunk
        parts = SENTENCE_SPLIT_REGEX.split(buffer)
        if len(parts) > 1:
            for sentence in parts[:-1]:
                clean = sentence.strip()
                if clean:
                    yield clean + "\n\n"
            buffer = parts[-1]

    remaining = buffer.strip()
    if remaining:
        yield remaining + "\n"


async def stream_audio_chunks(query: str, asset_id: str, voice: str, thread_id: str) -> AsyncGenerator[bytes, None]:
    """Converts buffered agent text chunks into PCM audio bytes via Kokoro TTS."""
    synth_fn = getattr(tts_provider, "synthesize_stream_bytes", getattr(tts_provider, "synthesize", None))
    async for sentence in stream_graph_sentences(query, asset_id, thread_id):
        clean_text = re.sub(r"\[\d+(?:-\d+)?\]", "", sentence)
        clean_text = re.sub(r"[*#_`]", "", clean_text).strip()
        if clean_text and synth_fn:
            audio_bytes = await asyncio.to_thread(synth_fn, clean_text, voice)
            if audio_bytes and isinstance(audio_bytes, (bytes, bytearray)):
                yield bytes(audio_bytes)


@app.post("/agent/stream-text")
async def agent_text_endpoint(req: AgentQueryRequest):
    """Streams sentence chunks generated by the LangGraph agent."""
    return StreamingResponse(
        stream_graph_sentences(req.query, req.asset_id, req.thread_id),
        media_type="text/plain",
    )


@app.post("/agent/stream-audio")
async def agent_audio_endpoint(req: AgentQueryRequest):
    """Streams synthesized PCM audio directly from text input."""
    return StreamingResponse(
        stream_audio_chunks(req.query, req.asset_id, req.voice, req.thread_id),
        media_type="audio/pcm",
    )


@app.post("/stt/transcribe")
async def transcribe_endpoint(file: UploadFile = File(...)):
    """Transcribes an uploaded audio file using Qwen3-ASR."""
    suffix = f".{file.filename.split('.')[-1]}" if "." in (file.filename or "") else ".wav"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(await file.read())
        tmp_path = tmp.name

    try:
        transcription_fn = getattr(stt_provider, "transcribe_with_language", getattr(stt_provider, "transcribe", None))
        result = await asyncio.to_thread(transcription_fn, tmp_path)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    if isinstance(result, dict):
        return result
    return {"text": str(result)}


@app.post("/agent/speech-to-speech")
async def speech_to_speech_endpoint(
    file: UploadFile = File(...),
    asset_id: str = Form("22"),
    voice: str = Form("af_heart"),
    thread_id: str = Form("voice_session"),
):
    """End-to-End Voice Pipeline via HTTP multipart upload."""
    suffix = f".{file.filename.split('.')[-1]}" if "." in (file.filename or "") else ".wav"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(await file.read())
        tmp_path = tmp.name

    try:
        transcription = await asyncio.to_thread(stt_provider.transcribe, tmp_path)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    transcribed_text = transcription.get("text", "") if isinstance(transcription, dict) else str(transcription or "")
    transcribed_text = transcribed_text.strip()
    if not transcribed_text:
        raise HTTPException(status_code=400, detail="No speech detected in audio file.")

    safe_header_text = urllib.parse.quote(transcribed_text)
    return StreamingResponse(
        stream_audio_chunks(
            query=transcribed_text,
            asset_id=asset_id,
            voice=voice,
            thread_id=thread_id,
        ),
        media_type="audio/pcm",
        headers={"X-Transcribed-Text": safe_header_text},
    )


@app.websocket("/ws/converse")
async def converse_ws(ws: WebSocket):
    """Full-duplex WebSocket for realtime speech-to-speech and text chat."""
    await ws.accept()
    synth_fn = getattr(tts_provider, "synthesize_stream_bytes", getattr(tts_provider, "synthesize", None))

    try:
        while True:
            msg = await ws.receive_json()

            if msg.get("type") == "audio":
                import base64
                wav_bytes = base64.b64decode(msg["data"])
                with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
                    tmp.write(wav_bytes)
                    tmp_path = tmp.name

                try:
                    transcription = await asyncio.to_thread(stt_provider.transcribe, tmp_path)
                finally:
                    if os.path.exists(tmp_path):
                        os.remove(tmp_path)

                query = transcription.get("text", "") if isinstance(transcription, dict) else str(transcription or "")
                query = query.strip()
                await ws.send_json({"type": "transcript", "data": query})

                if not query:
                    await ws.send_json({"type": "text_chunk", "data": "No speech detected. Please try again.\n"})
                    await ws.send_json({"type": "done"})
                    continue
            else:
                query = msg.get("data", "").strip()

            asset_id = msg.get("asset_id", "22")
            thread_id = msg.get("thread_id", "default_session")
            voice = msg.get("voice", "af_heart")

            async for sentence in stream_graph_sentences(query, asset_id, thread_id):
                await ws.send_json({"type": "text_chunk", "data": sentence})
                clean = re.sub(r"\[\d+(?:-\d+)?\]", "", sentence)
                clean = re.sub(r"[*#_`]", "", clean).strip()

                if clean and synth_fn:
                    pcm = await asyncio.to_thread(synth_fn, clean, voice)
                    if pcm:
                        wav = pcm_to_wav_bytes(pcm)
                        import base64
                        await ws.send_json({"type": "audio_chunk", "data": base64.b64encode(wav).decode()})

            await ws.send_json({"type": "done"})
    except WebSocketDisconnect:
        pass


@app.get("/")
async def serve_index():
    index_file = FRONTEND_DIR / "index.html"
    if not index_file.is_file():
        raise HTTPException(status_code=404, detail=f"index.html not found in {FRONTEND_DIR}")
    return FileResponse(index_file)


app.mount("/", StaticFiles(directory=str(FRONTEND_DIR), html=True), name="frontend")

